name: CI


# We want to build on all branches and pull requests
#
# @see https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
      with:
        submodules: true

    # Native (Linux amd64 Clang)
    - name: Linux amd64 Clang
      run: docker run --volume $GITHUB_WORKSPACE:/source:ro --volume $GITHUB_WORKSPACE/target:/target fedora:33 /source/.github/workflows/linux-amd64-clang.sh
    
    # Native (Linux amd64 GCC)
    - name: Linux amd64 GCC
      run: docker run --volume $GITHUB_WORKSPACE:/source:ro --volume $GITHUB_WORKSPACE/target:/target fedora:33 /source/.github/workflows/linux-amd64-gcc.sh

    # Cross compilation (Windows amd64 mingw)
    - name: Windows amd64 mingw
      run: docker run --volume $GITHUB_WORKSPACE:/source:ro --volume $GITHUB_WORKSPACE/target:/target fedora:33 /source/.github/workflows/windows-amd64-mingw.sh

    # Cross compilation (Windows amd64 mingw)
    - name: Windows i686 mingw
      run: docker run --volume $GITHUB_WORKSPACE:/source:ro --volume $GITHUB_WORKSPACE/target:/target fedora:33 /source/.github/workflows/windows-i686-mingw.sh

    # Test
    - name: test
      run: ls -la target
